// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH32oLDBFi0O_C8hTubmBXOhmwgaiLXMs',
    appId: '1:594375570551:web:b418411a57aaa870964272',
    messagingSenderId: '594375570551',
    projectId: 'electricity-bill-notifications',
    authDomain: 'electricity-bill-notifications.firebaseapp.com',
    storageBucket: 'electricity-bill-notifications.firebasestorage.app',
    measurementId: 'G-524X3PVTPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc9DKBcRpptF4gMbD_LAqa4D9ZyUwzTmk',
    appId: '1:594375570551:android:9d512ef687dd317b964272',
    messagingSenderId: '594375570551',
    projectId: 'electricity-bill-notifications',
    storageBucket: 'electricity-bill-notifications.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfz-bhHp7uDSh5gD5UKQspTXTtK6iwxHQ',
    appId: '1:594375570551:ios:156ab3594beecf1e964272',
    messagingSenderId: '594375570551',
    projectId: 'electricity-bill-notifications',
    storageBucket: 'electricity-bill-notifications.firebasestorage.app',
    iosBundleId: 'com.example.customer',
  );
}
